services:
  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: hw_example
    volumes:
      - hwdata:/var/lib/postgresql/data
  fastapi:
    build: ./
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - ./app:/code/app
    depends_on:
      - postgresdb
volumes:
  hwdata:
